// Visitor-facing descriptions of the authored collection. Geometric subjects
// are deliberately distinguished from scanned or measured museum specimens.
export const COLLECTION = {
 D01:['A neck across the gallery','Follow the sequence of neck vertebrae from the compact head back to the rib cage. This Mamenchisaurus-inspired skeletal reconstruction carries its neck over the central passage. Walk around the support islands to compare the long neck, trunk and tapering tail.'],
 D02:['A predator in profile','The open skull, tooth rows, deep rib cage and long balancing tail are the focus of this Tarbosaurus-inspired reconstruction. Look for the small two-fingered hands beneath the shoulder girdle.'],
 D03:['Armour in bone','This compact armoured-dinosaur reconstruction combines a rib cage with rows of sculpted osteoderms and lateral spikes. The arrangement is an interpretive study, rather than a reconstruction of a named individual.'],
 D04:['A smaller horned relative','A Protoceratops-inspired reconstruction at a more intimate viewing scale. Compare its beak and neck frill with the larger Triceratops study in Last Giants.'],
 D05:['A trail through stone','An original teaching cast with three shallow, three-toed impressions. Light across the surface reveals the track shapes. These marks were modelled for this display; they are not a cast of an excavated trackway.'],
 D06:['The shape of a tooth','Five original tooth casts present curved crowns, roots and serrated edges. The enlarged forms make small surface details easier to compare.'],
 D07:['A different prehistoric giant','A Diprotodon-inspired skeletal study represents the museum’s Australian megafauna theme. It is a mammal reconstruction, distinct from the dinosaurs elsewhere in this hall.'],
 D08:['Bones of a wing','A suspended pterosaur skeletal study reveals elongated wing fingers, a narrow rib cage and a long beak. Pterosaurs were flying reptiles, not dinosaurs. The cables belong to the display mount.'],
 D09:['Spirals on the overlook','Four original ammonite-inspired casts show coiled shells and repeated ribs. Compare the spiral forms from the elevated viewing position.'],
 B01:['Wings in variation','Eight enlarged butterfly studies pair coloured wing fields with dark margins, veins and small submarginal markings. These are original pattern studies, not a taxonomic series of named species.'],
 B02:['The beetle cabinet','A series of enlarged beetle studies explores wing cases, antennal shapes and mandibles. Scarab, stag-beetle and longhorn-inspired forms share a six-legged body plan.'],
 B03:['Contrasting forms','Two enlarged beetles emphasise very different structures: extended mandibles and long antennae. This display makes no largest, heaviest or longest specimen claim.'],
 B04:['Three insect body plans','Compare the beetle, butterfly and ant studies on this table. Their external forms highlight different proportions and appendages. The models are enlarged for inspection.'],
 B05:['A nest among leaves','A green-tree-ant-inspired diorama combines folded leaves, fine silk seams, a branch and a line of model ants. It is a static ecological illustration, not a living enclosure.'],
 B06:['The mantid’s folded forelegs','Look for the triangular head, long prothorax and folded, spined forelegs of this enlarged mantid study. Branches and foliage provide a setting for its pose.'],
 B07:['Below the water surface','An aquatic teaching diorama pairs an enlarged beetle with coiled gastropod models, stones and aquatic foliage. View through the sides of the case to inspect the small subjects.'],
 B08:['Life in the litter','Segmented millipede models wind between leaves, wood and fungi. Repeated pairs of small legs reward a close look at this static decomposer diorama.'],
 B09:['Inside the wing cases','An enlarged beetle study opens the hard wing cases to reveal the hind wings beneath. Look closely at the wing veins, abdominal plates, jointed legs, antennae and paired claws. Presentation length is about three metres; this is an enlarged teaching model.'],
 B10:['Three ways to examine mouthparts','Separate head studies present curved mandibles, a coiled proboscis and a slender stylet. These enlarged interpretive forms invite comparison of shape; they are not dissections of named specimens.'],
 B11:['Four stages, four forms','An original sequence presents eggs on a leaf, a segmented larval model, a pupal form and an adult butterfly study. The sequence illustrates complete metamorphosis without claiming to document a particular species.'],
 B12:['At the flower','An enlarged butterfly and open flowers form a close-view study of the insect–flower relationship. Small sculpted grains on the flower centres represent pollen.'],
 B13:['Two arachnid forms','Compare the eight-legged spider with the scorpion study beside it. The scorpion’s pedipalps form pincers and its segmented tail ends in a telson.'],
 B14:['A close look at a tarantula','An enlarged tarantula-inspired model includes eight walking legs, pedipalps and fine sculpted setae. The surrounding substrate and shelter form a static display.'],
 B15:['A spider on silk','A small orb-weaver-inspired model sits among radial silk and a capture spiral. This is a general web study; it does not identify a local species.'],
 B16:['Reading a web','Two original silk studies contrast a regular spiral with a more irregular pattern. Move across the cabinet to pick out the fine threads against the backing.'],
 F01:['The frill and the horns','Walk around this Smithsonian Triceratops horridus model to compare the broad frill, brow horns, beak and skeleton. The original 150,000-triangle model is credited to the Smithsonian Institution and distributed under CC0 through Wikimedia Commons. We reoriented it for this gallery and added a fossil-toned material; its source dimensions are preserved.'],
 F02:['From matrix to display','An original rock-matrix panel combines fossil-inspired forms with three preparation-tool models. The arrangement illustrates the preparation theme without representing an actual excavation.'],
 L01:['A table for comparison','Original spiral-shell casts and a small beetle model bring contrasting forms together at table height. These are digital teaching objects; touch interaction is not simulated.'],
 L02:['The microscope station','An original microscope model includes a focus mechanism, stage clips, a slide, objective lenses and an eyepiece. Small specimen dishes complete the station. This is a static display, not a working optical simulation.'],
 C01:['Tree ferns in the court','Three sculpted tree ferns rise above smaller ground ferns. Their trunks and divided fronds add planting to the central court while leaving the side routes open.'],
};
export const COLLECTION_NOTE='Original interpretive model. Anatomy, proportions and display scale are approximate; this is not a digitised collection specimen.';
